### ISSUE TITLE
Webpack cofiguration not updated

### ISSUE THREAD

**Issue by hacktar** [otoco-io/OtoCo-Gatsby#24]
After `gatsby develop` i received the following error:

> WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API 
  schema. 
configuration.resolve has an unknown property 'fallback'.

**Comment by filipesoccol** [comment]
Hi. This kind of issue is usually generated by Gatsby itself when some global module not match the one required by Gatsby.
I'll suggest you to check:
1) Node version installed `16.4.0`
2) Sass installed globally `sass@1.34.0`

Also, if you had run it previously and now it is stuck, maybe is needed to clean Gatsby cache using: `gatsby clean`

In case nothing works, just tell me and I'll update all packages inside project. Gatsby is a little strict with package versions.
